

services:
  app:
    build: .
    ports:
      - "4001:4001"  # Users service
      - "4002:4002"  # Clients service
      - "4003:4003"  # Projects service
      - "5001:5001"  # Gateway
      - "5173:5173"  # Web client (Vite)
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DATABASE_URL_CLIENTS: postgresql://user:password@postgres:5432/project_mngmnt_clients
      DATABASE_URL_USERS: postgresql://user:password@postgres:5432/project_mngmnt_users
      DATABASE_URL_PROJECTS: postgresql://user:password@postgres:5432/project_mngmnt_projects
     
      # Explicitly set DATABASE_URL for each service (to override .env)
      #DATABASE_URL: postgresql://user:password@postgres:5432/project_mngmnt_users  # Default to users; we'll map in code

    depends_on:
      - postgres
    command: sh -c "\
      pnpm --filter users-service exec prisma migrate deploy && pnpm --filter users-service exec prisma db seed && \
      pnpm --filter projects-service exec prisma migrate deploy && pnpm --filter projects-service exec prisma db seed && \
      pnpm --filter clients-service exec prisma migrate deploy && pnpm --filter clients-service exec prisma db seed && \
      pnpm run start-all"


  postgres:
    # ... (keep as is, but add healthcheck below for reliability)
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:  # Add this for better startup reliability
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

